name: Auto Merge Clean

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - name: Check merge-base with main
        id: mergebase
        run: |
          git fetch origin main
          if git merge-base --is-ancestor origin/main HEAD; then
            echo "clean=true" >> "$GITHUB_OUTPUT"
          else
            echo "clean=false" >> "$GITHUB_OUTPUT"
          fi
      - name: Lint
        run: npx eslint .
      - run: npm test
      - name: Auto merge PR
        if: steps.mergebase.outputs.clean == 'true'
        run: gh pr merge ${{ github.event.pull_request.number }} --merge --auto
        env:
          GITHUB_TOKEN: ${{ github.token }}
