name: Deploy to Cloud Run
# Main branch deployments push the SaaS platform to staging.
# Keeping a simple pipeline ensures quick iteration while we
# ramp up freemium, Pro, and Enterprise tiers on our .ai domain.

on:
  push:
    branches: [ main ]

env:
  PROJECT_ID: ai-agent-systems
  REGION: us-central1
  SERVICE_NAME: ai-agent-systems
  IMAGE: gcr.io/ai-agent-systems/ai-agent-systems

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GIT_TERMINAL_PROMPT: 0
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - name: Stub Firebase env vars
        run: |
          echo "VITE_FIREBASE_API_KEY=${VITE_FIREBASE_API_KEY:-dummy}" >> $GITHUB_ENV
          echo "VITE_FIREBASE_AUTH_DOMAIN=${VITE_FIREBASE_AUTH_DOMAIN:-dummy}" >> $GITHUB_ENV
          echo "VITE_FIREBASE_PROJECT_ID=${VITE_FIREBASE_PROJECT_ID:-dummy}" >> $GITHUB_ENV
        env:
          VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
          VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
          VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
      - run: npm run lint --if-present
      - run: npm test --if-present
      - id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCLOUD_SERVICE_KEY }}
      - uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}
      - name: Build Docker image
        run: gcloud builds submit --tag $IMAGE .
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $SERVICE_NAME \
            --image $IMAGE \
            --region $REGION \
            --platform managed \
            --allow-unauthenticated \
            --quiet
      - name: Post-deploy summary
        run: |
          npm run postdeploy:cloudrun
          npm run postdeploy:summary

      - name: Verify HTTPS on .ai domain
        run: node scripts/checkDomainHttps.js opspilot.ai

      - name: Tag release
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git tag -a "deploy-$GITHUB_RUN_NUMBER" -m "Automated deploy"
          git push origin "deploy-$GITHUB_RUN_NUMBER"
