name: Detect PR Conflicts

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check-conflicts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Fetch main
        run: git fetch origin main
      - name: Detect merge conflicts
        id: detect
        run: |
          git merge --no-commit --no-ff origin/main || true
          git diff --name-only --diff-filter=U > conflicts.txt
          git merge --abort || true
          echo "conflict_files<<EOF" >> "$GITHUB_OUTPUT"
          cat conflicts.txt >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"
      - name: Comment on PR if conflicts
        if: steps.detect.outputs.conflict_files != ''
        uses: actions/github-script@v7
        with:
          github-token: ${{ github.token }}
          script: |
            const files = `${{ steps.detect.outputs.conflict_files }}`.trim().split(/\n+/).filter(Boolean);
            const body = [
              '⚠️ Merge conflicts detected with `main`:',
              '',
              ...files.map(f => `- \`${f}\``)
            ].join('\n');
            await github.rest.issues.createComment({
              ...context.repo,
              issue_number: context.issue.number,
              body
            });
