name: Vercel PR Preview

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel
        id: vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          vercel --prod=false --confirm > deploy-url.txt
          echo "preview_url=$(tail -n1 deploy-url.txt)" >> "$GITHUB_OUTPUT"

      - name: Comment preview URL
        uses: actions/github-script@v7
        with:
          github-token: ${{ github.token }}
          script: |
            const url = process.env.PREVIEW_URL;
            const pr = context.payload.pull_request.number;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr,
              body: `Vercel Preview: ${url}`
            });
        env:
          PREVIEW_URL: ${{ steps.vercel.outputs.preview_url }}
